# Generated by Django 6.0.1 on 2026-01-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='records_stu_classro_651104_idx',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('user', 'classroom')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['user', 'classroom'], name='records_stu_user_id_2135a8_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['classroom'], name='records_stu_classro_570a37_idx'),
        ),
    ]
