# Generated by Django 6.0.1 on 2026-01-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_student_unique_user_per_year_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'School Admin'), ('teacher', 'Teacher'), ('student', 'Student')], db_index=True, default=None, max_length=20, null=True),
        ),
    ]
