# Generated by Django 6.0.1 on 2026-01-26 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_absences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('available_for_proxy', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='records.school')),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], db_index=True, max_length=10)),
                ('period', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='assigned', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='records.absence')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_proxies', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.classroom')),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_absences', to='records.teacher')),
                ('proxy_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_assignments', to='records.teacher')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='absence',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='records.teacher'),
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], db_index=True, max_length=10)),
                ('period', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='records.classroom')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='records.teacher')),
            ],
            options={
                'ordering': ['day', 'period'],
            },
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school', 'available_for_proxy'], name='records_tea_school__e48e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['user'], name='records_tea_user_id_deda48_idx'),
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['date', 'status'], name='records_pro_date_82525b_idx'),
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['proxy_teacher', 'status'], name='records_pro_proxy_t_5793d6_idx'),
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['original_teacher', 'date'], name='records_pro_origina_f52bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['classroom', 'date'], name='records_pro_classro_ea8f32_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['teacher', 'date'], name='records_abs_teacher_f2f28d_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['date', 'status'], name='records_abs_date_394417_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['teacher', 'status'], name='records_abs_teacher_fa11e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('teacher', 'date')},
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['classroom', 'day'], name='records_tim_classro_e66415_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['teacher', 'day'], name='records_tim_teacher_90b34a_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['classroom', 'day', 'period'], name='records_tim_classro_67248a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('classroom', 'day', 'period')},
        ),
    ]
