# Generated by Django 6.0.1 on 2026-01-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_absence_teacher_proxy_absence_teacher_timetableentry_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='absence',
            name='records_abs_teacher_f2f28d_idx',
        ),
        migrations.RemoveIndex(
            model_name='absence',
            name='records_abs_date_394417_idx',
        ),
        migrations.RemoveIndex(
            model_name='absence',
            name='records_abs_teacher_fa11e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='proxy',
            name='records_pro_date_82525b_idx',
        ),
        migrations.RemoveIndex(
            model_name='proxy',
            name='records_pro_proxy_t_5793d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='proxy',
            name='records_pro_origina_f52bbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='proxy',
            name='records_pro_classro_ea8f32_idx',
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='timetableentry',
            name='records_tim_classro_e66415_idx',
        ),
        migrations.RemoveIndex(
            model_name='timetableentry',
            name='records_tim_teacher_90b34a_idx',
        ),
        migrations.RemoveIndex(
            model_name='timetableentry',
            name='records_tim_classro_67248a_idx',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='absence',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='original_teacher',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='proxy_teacher',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Absence',
        ),
        migrations.DeleteModel(
            name='Proxy',
        ),
        migrations.DeleteModel(
            name='TimetableEntry',
        ),
    ]
