# Generated by Django 6.0.1 on 2026-01-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_absence_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teacher',
            name='records_tea_school__e48e7f_idx',
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school'], name='records_tea_school__c88122_idx'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='available_for_proxy',
        ),
    ]
