# Generated by Django 6.0.1 on 2026-01-26 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0006_alter_absence_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_absences', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='records.teacher')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], db_index=True, max_length=10)),
                ('period', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='assigned', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='timetable.absence')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_proxies', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.classroom')),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_absences', to='records.teacher')),
                ('proxy_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_assignments', to='records.teacher')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], db_index=True, max_length=10)),
                ('period', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='records.classroom')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='records.teacher')),
            ],
            options={
                'ordering': ['day', 'period'],
            },
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['teacher', 'date'], name='timetable_a_teacher_25b6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['date', 'status'], name='timetable_a_date_6d8544_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['teacher', 'status'], name='timetable_a_teacher_da9008_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('teacher', 'date')},
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['date', 'status'], name='timetable_p_date_71b026_idx'),
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['proxy_teacher', 'status'], name='timetable_p_proxy_t_6a2d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['original_teacher', 'date'], name='timetable_p_origina_55c106_idx'),
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['classroom', 'date'], name='timetable_p_classro_16d7db_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['classroom', 'day'], name='timetable_t_classro_de48b0_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['teacher', 'day'], name='timetable_t_teacher_da3f29_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['classroom', 'day', 'period'], name='timetable_t_classro_4a2287_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableentry',
            unique_together={('classroom', 'day', 'period')},
        ),
    ]
