# Generated by Django 6.0.1 on 2026-01-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_absence_unique_together_and_more'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], db_index=True, default='present', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher Attendance',
                'verbose_name_plural': 'Teacher Attendances',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='absence',
            name='timetable_a_teacher_25b6e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='absence',
            name='timetable_a_date_6d8544_idx',
        ),
        migrations.RemoveIndex(
            model_name='absence',
            name='timetable_a_teacher_da9008_idx',
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='records.teacher'),
        ),
        migrations.RemoveField(
            model_name='absence',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='teacher',
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['teacher', 'date'], name='timetable_t_teacher_8c0d67_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['date', 'status'], name='timetable_t_date_ffd16b_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['teacher', 'status'], name='timetable_t_teacher_b17680_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('teacher', 'date')},
        ),
        migrations.DeleteModel(
            name='Absence',
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
            ],
            options={
                'verbose_name': 'Absence Record',
                'verbose_name_plural': 'Absence Records',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('timetable.teacherattendance',),
        ),
    ]
